export const districtsPalhoca = [
  "Alto Aririú",
  "Área Rural de Palhoça",
  "Aririú",
  "Aririú da Formiga",
  "Balneário Ponta do Papagaio",
  "Barra do Aririú",
  "Bela Vista",
  "Brejarú",
  "Caminho Novo",
  "Centro",
  "Cidade Universitária Pedra Branca",
  "Enseada do Brito",
  "Guarda do Cubatão",
  "Guarda do Embaú",
  "Jardim Aquarius",
  "Jardim Coqueiros",
  "Jardim das Palmeiras",
  "Jardim Eldorado",
  "Madri",
  "Mar Azul",
  "Morretes",
  "Nova Palhoça",
  "Pagani",
  "Pachecos",
  "Passa Vinte",
  "Passagem de Maciambú",
  "Pedra Branca",
  "Pinheira",
  "Ponte do Imaruim",
  "Praia de Fora",
  "Praia do Meio",
  "Praia do Sonho",
  "Rio Grande",
  "São Sebastião",
  "Terra Fraca"
]